package net.epitap.degeneracycraft.datagen;

import net.epitap.degeneracycraft.Degeneracycraft;
import net.epitap.degeneracycraft.item.DCItems;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.tags.BlockTagsProvider;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;

public class DCItemtagProvider extends ItemTagsProvider {
        public DCItemtagProvider(DataGenerator generator, BlockTagsProvider blockTags, ExistingFileHelper helper) {
            super(generator, blockTags, Degeneracycraft.MOD_ID, helper);
        }

        @Override
        protected void addTags() {

            tag(DCItems.BERYL_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_BERYL_ORE.get())
                    .add(DCItems.BERYL_DUST.get())
                    .add(DCItems.BERYL_PUREDUST.get())
                    .add(DCItems.BERYL_LEACHATE.get())
                    .add(DCItems.BERYL_CONCENTRATE.get())
                    .add(DCItems.BERYL_PLASMA.get())
                    .add(DCItems.BERYL_DEGENERATEMATTER.get())
                    .add(DCItems.BERYL_SOUP.get())
                    .add(DCItems.BERYL_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_BERYL_IMAGINARYMATTER.get())
                    .add(DCItems.BERYL_TACHYON.get())
                    .add(DCItems.BERYL_ANTIMATTER.get())
                    .add(DCItems.BERYL_ULTRAHOTPLASMA.get())
                    .add(DCItems.BERYL_OVERFLUID.get())
                    .add(DCItems.BERYL_CRYSTAL.get())
                    .add(DCItems.BERYL_PRECIPITATE.get())
                    .add(DCItems.BERYL_WASHEDDUST.get())
                    .add(DCItems.BERYL_ORESINTER.get())
                    .add(DCItems.BERYL_INGOT.get());
            //
            tag(DCItems.BORAX_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_BORAX_ORE.get())
                    .add(DCItems.BORAX_DUST.get())
                    .add(DCItems.BORAX_PUREDUST.get())
                    .add(DCItems.BORAX_LEACHATE.get())
                    .add(DCItems.BORAX_CONCENTRATE.get())
                    .add(DCItems.BORAX_PLASMA.get())
                    .add(DCItems.BORAX_DEGENERATEMATTER.get())
                    .add(DCItems.BORAX_SOUP.get())
                    .add(DCItems.BORAX_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_BORAX_IMAGINARYMATTER.get())
                    .add(DCItems.BORAX_TACHYON.get())
                    .add(DCItems.BORAX_ANTIMATTER.get())
                    .add(DCItems.BORAX_ULTRAHOTPLASMA.get())
                    .add(DCItems.BORAX_OVERFLUID.get())
                    .add(DCItems.BORAX_CRYSTAL.get())
                    .add(DCItems.BORAX_PRECIPITATE.get())
                    .add(DCItems.BORAX_WASHEDDUST.get())
                    .add(DCItems.BORAX_ORESINTER.get())
                    .add(DCItems.BORAX_INGOT.get());
            //
            tag(DCItems.BAUXITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_BAUXITE_ORE.get())
                    .add(DCItems.BAUXITE_DUST.get())
                    .add(DCItems.BAUXITE_PUREDUST.get())
                    .add(DCItems.BAUXITE_LEACHATE.get())
                    .add(DCItems.BAUXITE_CONCENTRATE.get())
                    .add(DCItems.BAUXITE_PLASMA.get())
                    .add(DCItems.BAUXITE_DEGENERATEMATTER.get())
                    .add(DCItems.BAUXITE_SOUP.get())
                    .add(DCItems.BAUXITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_BAUXITE_IMAGINARYMATTER.get())
                    .add(DCItems.BAUXITE_TACHYON.get())
                    .add(DCItems.BAUXITE_ANTIMATTER.get())
                    .add(DCItems.BAUXITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.BAUXITE_OVERFLUID.get())
                    .add(DCItems.BAUXITE_CRYSTAL.get())
                    .add(DCItems.BAUXITE_PRECIPITATE.get())
                    .add(DCItems.BAUXITE_WASHEDDUST.get())
                    .add(DCItems.BAUXITE_ORESINTER.get())
                    .add(DCItems.BAUXITE_INGOT.get());
            //
            tag(DCItems.CASSITERITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_CASSITERITE_ORE.get())
                    .add(DCItems.CASSITERITE_DUST.get())
                    .add(DCItems.CASSITERITE_PUREDUST.get())
                    .add(DCItems.CASSITERITE_LEACHATE.get())
                    .add(DCItems.CASSITERITE_CONCENTRATE.get())
                    .add(DCItems.CASSITERITE_PLASMA.get())
                    .add(DCItems.CASSITERITE_DEGENERATEMATTER.get())
                    .add(DCItems.CASSITERITE_SOUP.get())
                    .add(DCItems.CASSITERITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_CASSITERITE_IMAGINARYMATTER.get())
                    .add(DCItems.CASSITERITE_TACHYON.get())
                    .add(DCItems.CASSITERITE_ANTIMATTER.get())
                    .add(DCItems.CASSITERITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.CASSITERITE_OVERFLUID.get())
                    .add(DCItems.CASSITERITE_CRYSTAL.get())
                    .add(DCItems.CASSITERITE_PRECIPITATE.get())
                    .add(DCItems.CASSITERITE_WASHEDDUST.get())
                    .add(DCItems.CASSITERITE_ORESINTER.get())
                    .add(DCItems.CASSITERITE_INGOT.get());
            //
            tag(DCItems.CHROMITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_CHROMITE_ORE.get())
                    .add(DCItems.CHROMITE_DUST.get())
                    .add(DCItems.CHROMITE_PUREDUST.get())
                    .add(DCItems.CHROMITE_LEACHATE.get())
                    .add(DCItems.CHROMITE_CONCENTRATE.get())
                    .add(DCItems.CHROMITE_PLASMA.get())
                    .add(DCItems.CHROMITE_DEGENERATEMATTER.get())
                    .add(DCItems.CHROMITE_SOUP.get())
                    .add(DCItems.CHROMITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_CHROMITE_IMAGINARYMATTER.get())
                    .add(DCItems.CHROMITE_TACHYON.get())
                    .add(DCItems.CHROMITE_ANTIMATTER.get())
                    .add(DCItems.CHROMITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.CHROMITE_OVERFLUID.get())
                    .add(DCItems.CHROMITE_CRYSTAL.get())
                    .add(DCItems.CHROMITE_PRECIPITATE.get())
                    .add(DCItems.CHROMITE_WASHEDDUST.get())
                    .add(DCItems.CHROMITE_ORESINTER.get())
                    .add(DCItems.CHROMITE_INGOT.get());
            //
            tag(DCItems.FLUORITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_FLUORITE_ORE.get())
                    .add(DCItems.FLUORITE_DUST.get())
                    .add(DCItems.FLUORITE_PUREDUST.get())
                    .add(DCItems.FLUORITE_LEACHATE.get())
                    .add(DCItems.FLUORITE_CONCENTRATE.get())
                    .add(DCItems.FLUORITE_PLASMA.get())
                    .add(DCItems.FLUORITE_DEGENERATEMATTER.get())
                    .add(DCItems.FLUORITE_SOUP.get())
                    .add(DCItems.FLUORITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_FLUORITE_IMAGINARYMATTER.get())
                    .add(DCItems.FLUORITE_TACHYON.get())
                    .add(DCItems.FLUORITE_ANTIMATTER.get())
                    .add(DCItems.FLUORITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.FLUORITE_OVERFLUID.get())
                    .add(DCItems.FLUORITE_CRYSTAL.get())
                    .add(DCItems.FLUORITE_PRECIPITATE.get())
                    .add(DCItems.FLUORITE_WASHEDDUST.get())
                    .add(DCItems.FLUORITE_ORESINTER.get())
                    .add(DCItems.FLUORITE_INGOT.get());
            //
            tag(DCItems.GRAPHITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_GRAPHITE_ORE.get())
                    .add(DCItems.GRAPHITE_DUST.get())
                    .add(DCItems.GRAPHITE_PUREDUST.get())
                    .add(DCItems.GRAPHITE_LEACHATE.get())
                    .add(DCItems.GRAPHITE_CONCENTRATE.get())
                    .add(DCItems.GRAPHITE_PLASMA.get())
                    .add(DCItems.GRAPHITE_DEGENERATEMATTER.get())
                    .add(DCItems.GRAPHITE_SOUP.get())
                    .add(DCItems.GRAPHITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_GRAPHITE_IMAGINARYMATTER.get())
                    .add(DCItems.GRAPHITE_TACHYON.get())
                    .add(DCItems.GRAPHITE_ANTIMATTER.get())
                    .add(DCItems.GRAPHITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.GRAPHITE_OVERFLUID.get())
                    .add(DCItems.GRAPHITE_CRYSTAL.get())
                    .add(DCItems.GRAPHITE_PRECIPITATE.get())
                    .add(DCItems.GRAPHITE_WASHEDDUST.get())
                    .add(DCItems.GRAPHITE_ORESINTER.get())
                    .add(DCItems.GRAPHITE_INGOT.get());
            //
//            tag(DCItems.IRON_MULTIPLIED_ORE_MATERIAL)
//                    .add(DCItems.IRON_DUST.get())
//                    .add(DCItems.IRON_PUREDUST.get())
//                    .add(DCItems.IRON_LEACHATE.get())
//                    .add(DCItems.IRON_CONCENTRATE.get())
//                    .add(DCItems.IRON_PLASMA.get())
//                    .add(DCItems.IRON_DEGENERATEMATTER.get())
//                    .add(DCItems.IRON_SOUP.get())
//                    .add(DCItems.IRON_IMAGINARYMATTER.get())
//                    .add(DCItems.STABLE_IRON_IMAGINARYMATTER.get())
//                    .add(DCItems.IRON_TACHYON.get())
//                    .add(DCItems.IRON_ANTIMATTER.get())
//                    .add(DCItems.IRON_ULTRAHOTPLASMA.get())
//                    .add(DCItems.IRON_OVERFLUID.get())
//                    .add(DCItems.IRON_CRYSTAL.get())
//                    .add(DCItems.IRON_PRECIPITATE.get())
//                    .add(DCItems.IRON_WASHEDDUST.get())
//                    .add(DCItems.IRON_ORESINTER.get());
            //
            tag(DCItems.LATERITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_LATERITE_ORE.get())
                    .add(DCItems.LATERITE_DUST.get())
                    .add(DCItems.LATERITE_PUREDUST.get())
                    .add(DCItems.LATERITE_LEACHATE.get())
                    .add(DCItems.LATERITE_CONCENTRATE.get())
                    .add(DCItems.LATERITE_PLASMA.get())
                    .add(DCItems.LATERITE_DEGENERATEMATTER.get())
                    .add(DCItems.LATERITE_SOUP.get())
                    .add(DCItems.LATERITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_LATERITE_IMAGINARYMATTER.get())
                    .add(DCItems.LATERITE_TACHYON.get())
                    .add(DCItems.LATERITE_ANTIMATTER.get())
                    .add(DCItems.LATERITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.LATERITE_OVERFLUID.get())
                    .add(DCItems.LATERITE_CRYSTAL.get())
                    .add(DCItems.LATERITE_PRECIPITATE.get())
                    .add(DCItems.LATERITE_WASHEDDUST.get())
                    .add(DCItems.LATERITE_ORESINTER.get())
                    .add(DCItems.LATERITE_INGOT.get());
            //
            tag(DCItems.LIMESTONE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_LIMESTONE_ORE.get())
                    .add(DCItems.LIMESTONE_DUST.get())
                    .add(DCItems.LIMESTONE_PUREDUST.get())
                    .add(DCItems.LIMESTONE_LEACHATE.get())
                    .add(DCItems.LIMESTONE_CONCENTRATE.get())
                    .add(DCItems.LIMESTONE_PLASMA.get())
                    .add(DCItems.LIMESTONE_DEGENERATEMATTER.get())
                    .add(DCItems.LIMESTONE_SOUP.get())
                    .add(DCItems.LIMESTONE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_LIMESTONE_IMAGINARYMATTER.get())
                    .add(DCItems.LIMESTONE_TACHYON.get())
                    .add(DCItems.LIMESTONE_ANTIMATTER.get())
                    .add(DCItems.LIMESTONE_ULTRAHOTPLASMA.get())
                    .add(DCItems.LIMESTONE_OVERFLUID.get())
                    .add(DCItems.LIMESTONE_CRYSTAL.get())
                    .add(DCItems.LIMESTONE_PRECIPITATE.get())
                    .add(DCItems.LIMESTONE_WASHEDDUST.get())
                    .add(DCItems.LIMESTONE_ORESINTER.get())
                    .add(DCItems.LIMESTONE_INGOT.get());
            //
            tag(DCItems.PEGMATITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_PEGMATITE_ORE.get())
                    .add(DCItems.PEGMATITE_DUST.get())
                    .add(DCItems.PEGMATITE_PUREDUST.get())
                    .add(DCItems.PEGMATITE_LEACHATE.get())
                    .add(DCItems.PEGMATITE_CONCENTRATE.get())
                    .add(DCItems.PEGMATITE_PLASMA.get())
                    .add(DCItems.PEGMATITE_DEGENERATEMATTER.get())
                    .add(DCItems.PEGMATITE_SOUP.get())
                    .add(DCItems.PEGMATITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_PEGMATITE_IMAGINARYMATTER.get())
                    .add(DCItems.PEGMATITE_TACHYON.get())
                    .add(DCItems.PEGMATITE_ANTIMATTER.get())
                    .add(DCItems.PEGMATITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.PEGMATITE_OVERFLUID.get())
                    .add(DCItems.PEGMATITE_CRYSTAL.get())
                    .add(DCItems.PEGMATITE_PRECIPITATE.get())
                    .add(DCItems.PEGMATITE_WASHEDDUST.get())
                    .add(DCItems.PEGMATITE_ORESINTER.get())
                    .add(DCItems.PEGMATITE_INGOT.get());
            //
            tag(DCItems.PHOSPHORITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_PHOSPHORITE_ORE.get())
                    .add(DCItems.PHOSPHORITE_DUST.get())
                    .add(DCItems.PHOSPHORITE_PUREDUST.get())
                    .add(DCItems.PHOSPHORITE_LEACHATE.get())
                    .add(DCItems.PHOSPHORITE_CONCENTRATE.get())
                    .add(DCItems.PHOSPHORITE_PLASMA.get())
                    .add(DCItems.PHOSPHORITE_DEGENERATEMATTER.get())
                    .add(DCItems.PHOSPHORITE_SOUP.get())
                    .add(DCItems.PHOSPHORITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_PHOSPHORITE_IMAGINARYMATTER.get())
                    .add(DCItems.PHOSPHORITE_TACHYON.get())
                    .add(DCItems.PHOSPHORITE_ANTIMATTER.get())
                    .add(DCItems.PHOSPHORITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.PHOSPHORITE_OVERFLUID.get())
                    .add(DCItems.PHOSPHORITE_CRYSTAL.get())
                    .add(DCItems.PHOSPHORITE_PRECIPITATE.get())
                    .add(DCItems.PHOSPHORITE_WASHEDDUST.get())
                    .add(DCItems.PHOSPHORITE_ORESINTER.get())
                    .add(DCItems.PHOSPHORITE_INGOT.get());
            //
            tag(DCItems.PYROLUSITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_PYROLUSITE_ORE.get())
                    .add(DCItems.PYROLUSITE_DUST.get())
                    .add(DCItems.PYROLUSITE_PUREDUST.get())
                    .add(DCItems.PYROLUSITE_LEACHATE.get())
                    .add(DCItems.PYROLUSITE_CONCENTRATE.get())
                    .add(DCItems.PYROLUSITE_PLASMA.get())
                    .add(DCItems.PYROLUSITE_DEGENERATEMATTER.get())
                    .add(DCItems.PYROLUSITE_SOUP.get())
                    .add(DCItems.PYROLUSITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_PYROLUSITE_IMAGINARYMATTER.get())
                    .add(DCItems.PYROLUSITE_TACHYON.get())
                    .add(DCItems.PYROLUSITE_ANTIMATTER.get())
                    .add(DCItems.PYROLUSITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.PYROLUSITE_OVERFLUID.get())
                    .add(DCItems.PYROLUSITE_CRYSTAL.get())
                    .add(DCItems.PYROLUSITE_PRECIPITATE.get())
                    .add(DCItems.PYROLUSITE_WASHEDDUST.get())
                    .add(DCItems.PYROLUSITE_ORESINTER.get())
                    .add(DCItems.PYROLUSITE_INGOT.get());
            //
            tag(DCItems.RUTILE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_RUTILE_ORE.get())
                    .add(DCItems.RUTILE_DUST.get())
                    .add(DCItems.RUTILE_PUREDUST.get())
                    .add(DCItems.RUTILE_LEACHATE.get())
                    .add(DCItems.RUTILE_CONCENTRATE.get())
                    .add(DCItems.RUTILE_PLASMA.get())
                    .add(DCItems.RUTILE_DEGENERATEMATTER.get())
                    .add(DCItems.RUTILE_SOUP.get())
                    .add(DCItems.RUTILE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_RUTILE_IMAGINARYMATTER.get())
                    .add(DCItems.RUTILE_TACHYON.get())
                    .add(DCItems.RUTILE_ANTIMATTER.get())
                    .add(DCItems.RUTILE_ULTRAHOTPLASMA.get())
                    .add(DCItems.RUTILE_OVERFLUID.get())
                    .add(DCItems.RUTILE_CRYSTAL.get())
                    .add(DCItems.RUTILE_PRECIPITATE.get())
                    .add(DCItems.RUTILE_WASHEDDUST.get())
                    .add(DCItems.RUTILE_ORESINTER.get())
                    .add(DCItems.RUTILE_INGOT.get());
            //
            tag(DCItems.SPODUMENE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_SPODUMENE_ORE.get())
                    .add(DCItems.SPODUMENE_DUST.get())
                    .add(DCItems.SPODUMENE_PUREDUST.get())
                    .add(DCItems.SPODUMENE_LEACHATE.get())
                    .add(DCItems.SPODUMENE_CONCENTRATE.get())
                    .add(DCItems.SPODUMENE_PLASMA.get())
                    .add(DCItems.SPODUMENE_DEGENERATEMATTER.get())
                    .add(DCItems.SPODUMENE_SOUP.get())
                    .add(DCItems.SPODUMENE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_SPODUMENE_IMAGINARYMATTER.get())
                    .add(DCItems.SPODUMENE_TACHYON.get())
                    .add(DCItems.SPODUMENE_ANTIMATTER.get())
                    .add(DCItems.SPODUMENE_ULTRAHOTPLASMA.get())
                    .add(DCItems.SPODUMENE_OVERFLUID.get())
                    .add(DCItems.SPODUMENE_CRYSTAL.get())
                    .add(DCItems.SPODUMENE_PRECIPITATE.get())
                    .add(DCItems.SPODUMENE_WASHEDDUST.get())
                    .add(DCItems.SPODUMENE_ORESINTER.get())
                    .add(DCItems.SPODUMENE_INGOT.get());
            //
            tag(DCItems.SYLVITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_SYLVITE_ORE.get())
                    .add(DCItems.SYLVITE_DUST.get())
                    .add(DCItems.SYLVITE_PUREDUST.get())
                    .add(DCItems.SYLVITE_LEACHATE.get())
                    .add(DCItems.SYLVITE_CONCENTRATE.get())
                    .add(DCItems.SYLVITE_PLASMA.get())
                    .add(DCItems.SYLVITE_DEGENERATEMATTER.get())
                    .add(DCItems.SYLVITE_SOUP.get())
                    .add(DCItems.SYLVITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_SYLVITE_IMAGINARYMATTER.get())
                    .add(DCItems.SYLVITE_TACHYON.get())
                    .add(DCItems.SYLVITE_ANTIMATTER.get())
                    .add(DCItems.SYLVITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.SYLVITE_OVERFLUID.get())
                    .add(DCItems.SYLVITE_CRYSTAL.get())
                    .add(DCItems.SYLVITE_PRECIPITATE.get())
                    .add(DCItems.SYLVITE_WASHEDDUST.get())
                    .add(DCItems.SYLVITE_ORESINTER.get())
                    .add(DCItems.SYLVITE_INGOT.get());
            //
            tag(DCItems.ULEXITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_ULEXITE_ORE.get())
                    .add(DCItems.ULEXITE_DUST.get())
                    .add(DCItems.ULEXITE_PUREDUST.get())
                    .add(DCItems.ULEXITE_LEACHATE.get())
                    .add(DCItems.ULEXITE_CONCENTRATE.get())
                    .add(DCItems.ULEXITE_PLASMA.get())
                    .add(DCItems.ULEXITE_DEGENERATEMATTER.get())
                    .add(DCItems.ULEXITE_SOUP.get())
                    .add(DCItems.ULEXITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_ULEXITE_IMAGINARYMATTER.get())
                    .add(DCItems.ULEXITE_TACHYON.get())
                    .add(DCItems.ULEXITE_ANTIMATTER.get())
                    .add(DCItems.ULEXITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.ULEXITE_OVERFLUID.get())
                    .add(DCItems.ULEXITE_CRYSTAL.get())
                    .add(DCItems.ULEXITE_PRECIPITATE.get())
                    .add(DCItems.ULEXITE_WASHEDDUST.get())
                    .add(DCItems.ULEXITE_ORESINTER.get())
                    .add(DCItems.ULEXITE_INGOT.get());
            //
            tag(DCItems.VANADINITE_MULTIPLIED_ORE_MATERIAL)
                    .add(DCItems.RAW_VANADINITE_ORE.get())
                    .add(DCItems.VANADINITE_DUST.get())
                    .add(DCItems.VANADINITE_PUREDUST.get())
                    .add(DCItems.VANADINITE_LEACHATE.get())
                    .add(DCItems.VANADINITE_CONCENTRATE.get())
                    .add(DCItems.VANADINITE_PLASMA.get())
                    .add(DCItems.VANADINITE_DEGENERATEMATTER.get())
                    .add(DCItems.VANADINITE_SOUP.get())
                    .add(DCItems.VANADINITE_IMAGINARYMATTER.get())
                    .add(DCItems.STABLE_VANADINITE_IMAGINARYMATTER.get())
                    .add(DCItems.VANADINITE_TACHYON.get())
                    .add(DCItems.VANADINITE_ANTIMATTER.get())
                    .add(DCItems.VANADINITE_ULTRAHOTPLASMA.get())
                    .add(DCItems.VANADINITE_OVERFLUID.get())
                    .add(DCItems.VANADINITE_CRYSTAL.get())
                    .add(DCItems.VANADINITE_PRECIPITATE.get())
                    .add(DCItems.VANADINITE_WASHEDDUST.get())
                    .add(DCItems.VANADINITE_ORESINTER.get())
                    .add(DCItems.VANADINITE_INGOT.get());
            //

            tag(DCItems.COPPER_MACHINE_COMPONENT)
                    .add(DCItems.COPPER_BOLT.get())
                    .add(DCItems.COPPER_KEY.get())
                    .add(DCItems.COPPER_ROD.get())
                    .add(DCItems.COPPER_SPRING.get())
                    .add(DCItems.COPPER_BEARING.get())
                    .add(DCItems.COPPER_PLATE.get())
                    .add(DCItems.COPPER_GEAR.get())
                    .add(DCItems.COPPER_JOINT.get())
                    .add(DCItems.COPPER_NUT.get())
                    .add(DCItems.COPPER_PIPE.get())
                    .add(DCItems.COPPER_PIPEJOINT.get())
                    .add(DCItems.COPPER_CAM.get())
                    .add(DCItems.COPPER_SHAFT.get())
                    .add(DCItems.COPPER_SHAFTCOUPLING.get())
                    .add(DCItems.COPPER_SHAPESTEEL.get())
                    .add(DCItems.COPPER_CHAIN.get());

//            tag(DCItems.BASIC_CLASS_IRON_MACHINE_COMPONENT)
//                    .add(DCItems.BASIC_CLASS_IRON_BEARING.get())
//                    .add(DCItems.BASIC_CLASS_IRON_BOLT.get())
//                    .add(DCItems.BASIC_CLASS_IRON_CAM.get())
//                    .add(DCItems.BASIC_CLASS_IRON_CHAIN.get())
//                    .add(DCItems.BASIC_CLASS_IRON_GEAR.get())
//                    .add(DCItems.BASIC_CLASS_IRON_JOINT.get())
//                    .add(DCItems.BASIC_CLASS_IRON_KEY.get())
//                    .add(DCItems.BASIC_CLASS_IRON_NUT.get())
//                    .add(DCItems.BASIC_CLASS_IRON_PIPE.get())
//                    .add(DCItems.BASIC_CLASS_IRON_PIPEJOINT.get())
//                    .add(DCItems.BASIC_CLASS_IRON_PLATE.get())
//                    .add(DCItems.BASIC_CLASS_IRON_ROD.get())
//                    .add(DCItems.BASIC_CLASS_IRON_SHAFT.get())
//                    .add(DCItems.BASIC_CLASS_IRON_SHAFTCOUPLING.get())
//                    .add(DCItems.BASIC_CLASS_IRON_SHAPESTEEL.get())
//                    .add(DCItems.BASIC_CLASS_IRON_SPRING.get());
//
//            tag(DCItems.LOW_CLASS_IRON_MACHINE_COMPONENT)
//                    .add(DCItems.LOW_CLASS_IRON_BEARING.get())
//                    .add(DCItems.LOW_CLASS_IRON_BOLT.get())
//                    .add(DCItems.LOW_CLASS_IRON_CAM.get())
//                    .add(DCItems.LOW_CLASS_IRON_CHAIN.get())
//                    .add(DCItems.LOW_CLASS_IRON_GEAR.get())
//                    .add(DCItems.LOW_CLASS_IRON_JOINT.get())
//                    .add(DCItems.LOW_CLASS_IRON_KEY.get())
//                    .add(DCItems.LOW_CLASS_IRON_NUT.get())
//                    .add(DCItems.LOW_CLASS_IRON_PIPE.get())
//                    .add(DCItems.LOW_CLASS_IRON_PIPEJOINT.get())
//                    .add(DCItems.LOW_CLASS_IRON_PLATE.get())
//                    .add(DCItems.LOW_CLASS_IRON_ROD.get())
//                    .add(DCItems.LOW_CLASS_IRON_SHAFT.get())
//                    .add(DCItems.LOW_CLASS_IRON_SHAFTCOUPLING.get())
//                    .add(DCItems.LOW_CLASS_IRON_SHAPESTEEL.get())
//                    .add(DCItems.LOW_CLASS_IRON_SPRING.get());
//
//            tag(DCItems.MEDIUM_CLASS_IRON_MACHINE_COMPONENT)
//                    .add(DCItems.MEDIUM_CLASS_IRON_BEARING.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_BOLT.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_CAM.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_CHAIN.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_GEAR.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_JOINT.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_KEY.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_NUT.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_PIPE.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_PIPEJOINT.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_PLATE.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_ROD.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_SHAFT.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_SHAFTCOUPLING.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_SHAPESTEEL.get())
//                    .add(DCItems.MEDIUM_CLASS_IRON_SPRING.get());
//
//            tag(DCItems.HIGH_CLASS_IRON_MACHINE_COMPONENT)
//                    .add(DCItems.HIGH_CLASS_IRON_BEARING.get())
//                    .add(DCItems.HIGH_CLASS_IRON_BOLT.get())
//                    .add(DCItems.HIGH_CLASS_IRON_CAM.get())
//                    .add(DCItems.HIGH_CLASS_IRON_CHAIN.get())
//                    .add(DCItems.HIGH_CLASS_IRON_GEAR.get())
//                    .add(DCItems.HIGH_CLASS_IRON_JOINT.get())
//                    .add(DCItems.HIGH_CLASS_IRON_KEY.get())
//                    .add(DCItems.HIGH_CLASS_IRON_NUT.get())
//                    .add(DCItems.HIGH_CLASS_IRON_PIPE.get())
//                    .add(DCItems.HIGH_CLASS_IRON_PIPEJOINT.get())
//                    .add(DCItems.HIGH_CLASS_IRON_PLATE.get())
//                    .add(DCItems.HIGH_CLASS_IRON_ROD.get())
//                    .add(DCItems.HIGH_CLASS_IRON_SHAFT.get())
//                    .add(DCItems.HIGH_CLASS_IRON_SHAFTCOUPLING.get())
//                    .add(DCItems.HIGH_CLASS_IRON_SHAPESTEEL.get())
//                    .add(DCItems.HIGH_CLASS_IRON_SPRING.get());
//
//            tag(DCItems.SUPER_CLASS_IRON_MACHINE_COMPONENT)
//                    .add(DCItems.SUPER_CLASS_IRON_BEARING.get())
//                    .add(DCItems.SUPER_CLASS_IRON_BOLT.get())
//                    .add(DCItems.SUPER_CLASS_IRON_CAM.get())
//                    .add(DCItems.SUPER_CLASS_IRON_CHAIN.get())
//                    .add(DCItems.SUPER_CLASS_IRON_GEAR.get())
//                    .add(DCItems.SUPER_CLASS_IRON_JOINT.get())
//                    .add(DCItems.SUPER_CLASS_IRON_KEY.get())
//                    .add(DCItems.SUPER_CLASS_IRON_NUT.get())
//                    .add(DCItems.SUPER_CLASS_IRON_PIPE.get())
//                    .add(DCItems.SUPER_CLASS_IRON_PIPEJOINT.get())
//                    .add(DCItems.SUPER_CLASS_IRON_PLATE.get())
//                    .add(DCItems.SUPER_CLASS_IRON_ROD.get())
//                    .add(DCItems.SUPER_CLASS_IRON_SHAFT.get())
//                    .add(DCItems.SUPER_CLASS_IRON_SHAFTCOUPLING.get())
//                    .add(DCItems.SUPER_CLASS_IRON_SHAPESTEEL.get())
//                    .add(DCItems.SUPER_CLASS_IRON_SPRING.get());
//
//            tag(DCItems.OVER_CLASS_IRON_MACHINE_COMPONENT)
//                    .add(DCItems.OVER_CLASS_IRON_BEARING.get())
//                    .add(DCItems.OVER_CLASS_IRON_BOLT.get())
//                    .add(DCItems.OVER_CLASS_IRON_CAM.get())
//                    .add(DCItems.OVER_CLASS_IRON_CHAIN.get())
//                    .add(DCItems.OVER_CLASS_IRON_GEAR.get())
//                    .add(DCItems.OVER_CLASS_IRON_JOINT.get())
//                    .add(DCItems.OVER_CLASS_IRON_KEY.get())
//                    .add(DCItems.OVER_CLASS_IRON_NUT.get())
//                    .add(DCItems.OVER_CLASS_IRON_PIPE.get())
//                    .add(DCItems.OVER_CLASS_IRON_PIPEJOINT.get())
//                    .add(DCItems.OVER_CLASS_IRON_PLATE.get())
//                    .add(DCItems.OVER_CLASS_IRON_ROD.get())
//                    .add(DCItems.OVER_CLASS_IRON_SHAFT.get())
//                    .add(DCItems.OVER_CLASS_IRON_SHAFTCOUPLING.get())
//                    .add(DCItems.OVER_CLASS_IRON_SHAPESTEEL.get())
//                    .add(DCItems.OVER_CLASS_IRON_SPRING.get());
//
//            tag(DCItems.ULTRA_CLASS_IRON_MACHINE_COMPONENT)
//                    .add(DCItems.ULTRA_CLASS_IRON_BEARING.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_BOLT.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_CAM.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_CHAIN.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_GEAR.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_JOINT.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_KEY.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_NUT.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_PIPE.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_PIPEJOINT.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_PLATE.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_ROD.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_SHAFT.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_SHAFTCOUPLING.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_SHAPESTEEL.get())
//                    .add(DCItems.ULTRA_CLASS_IRON_SPRING.get());
//
//            tag(DCItems.ANTI_CLASS_IRON_MACHINE_COMPONENT)
//                    .add(DCItems.ANTI_CLASS_IRON_BEARING.get())
//                    .add(DCItems.ANTI_CLASS_IRON_BOLT.get())
//                    .add(DCItems.ANTI_CLASS_IRON_CAM.get())
//                    .add(DCItems.ANTI_CLASS_IRON_CHAIN.get())
//                    .add(DCItems.ANTI_CLASS_IRON_GEAR.get())
//                    .add(DCItems.ANTI_CLASS_IRON_JOINT.get())
//                    .add(DCItems.ANTI_CLASS_IRON_KEY.get())
//                    .add(DCItems.ANTI_CLASS_IRON_NUT.get())
//                    .add(DCItems.ANTI_CLASS_IRON_PIPE.get())
//                    .add(DCItems.ANTI_CLASS_IRON_PIPEJOINT.get())
//                    .add(DCItems.ANTI_CLASS_IRON_PLATE.get())
//                    .add(DCItems.ANTI_CLASS_IRON_ROD.get())
//                    .add(DCItems.ANTI_CLASS_IRON_SHAFT.get())
//                    .add(DCItems.ANTI_CLASS_IRON_SHAFTCOUPLING.get())
//                    .add(DCItems.ANTI_CLASS_IRON_SHAPESTEEL.get())
//                    .add(DCItems.ANTI_CLASS_IRON_SPRING.get());
//
//            tag(DCItems.IMAGINARY_CLASS_IRON_MACHINE_COMPONENT)
//                    .add(DCItems.IMAGINARY_CLASS_IRON_BEARING.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_BOLT.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_CAM.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_CHAIN.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_GEAR.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_JOINT.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_KEY.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_NUT.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_PIPE.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_PIPEJOINT.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_PLATE.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_ROD.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_SHAFT.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_SHAFTCOUPLING.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_SHAPESTEEL.get())
//                    .add(DCItems.IMAGINARY_CLASS_IRON_SPRING.get());
//
//            tag(DCItems.INFINITY_CLASS_IRON_MACHINE_COMPONENT)
//                    .add(DCItems.INFINITY_CLASS_IRON_BEARING.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_BOLT.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_CAM.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_CHAIN.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_GEAR.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_JOINT.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_KEY.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_NUT.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_PIPE.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_PIPEJOINT.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_PLATE.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_ROD.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_SHAFT.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_SHAFTCOUPLING.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_SHAPESTEEL.get())
//                    .add(DCItems.INFINITY_CLASS_IRON_SPRING.get());
//
            tag(DCItems.MACHINE_COMPONENT_BASIC_PRECISION_CIRCUIT)
                    .add(DCItems.BASIC_PRECISION_BOLT_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_KEY_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_ROD_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_SPRING_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_BEARING_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_PLATE_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_GEAR_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_JOINT_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_NUT_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_PIPE_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_PIPEJOINT_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_CAM_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_SHAFT_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_SHAFTCOUPLING_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_SHAPESTEEL_INSCRIBED_CIRCUIT.get())
                    .add(DCItems.BASIC_PRECISION_CHAIN_INSCRIBED_CIRCUIT.get());
//            tag(Tags.Items.INGOTS)
//                    .add(DCItems.GRAVITATION_INGOT.get())
//                    .add(DCItems.CASSITERITE_INGOT.get());
        }
        public enum DCItemtag{
            IRON_BEARING
        }

        @Override
        public String getName() {
            return "DegeneracyCraft Tags";
        }
}
